# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7,7)
random_tensor.shape


torch.Size([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
random_tensor_2 = torch.rand(1,7)

# Perform matrix multiplication 
torch.mm(random_tensor, random_tensor_2.T)


tensor([[0.4382],
        [1.2257],
        [0.5375],
        [1.5832],
        [0.9519],
        [1.7283],
        [0.7342]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)
r1 = torch.rand(7, 7)

# Create two random tensors
torch.manual_seed(0)
r2 = torch.rand(1, 7)

# Matrix multiply tensors
torch.mm(r1, r2.T)


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(1)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
r3 = torch.rand(size=(10, 10), device=device)
r4 = torch.rand(size=(10, 10), device=device)
r3,r4

(tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903, 0.3394, 0.5451,
          0.7312],
         [0.3864, 0.5959, 0.7578, 0.2126, 0.7198, 0.9845, 0.5518, 0.0981, 0.0582,
          0.5839],
         [0.1083, 0.9461, 0.3170, 0.8328, 0.6676, 0.2886, 0.9022, 0.8115, 0.1784,
          0.9534],
         [0.1486, 0.3882, 0.7977, 0.1752, 0.5777, 0.1949, 0.8499, 0.3125, 0.2156,
          0.0383],
         [0.4934, 0.3138, 0.3121, 0.5664, 0.1266, 0.7097, 0.0040, 0.5147, 0.2811,
          0.4441],
         [0.0915, 0.3322, 0.3984, 0.9881, 0.0936, 0.3067, 0.0523, 0.2162, 0.0307,
          0.4602],
         [0.1048, 0.1429, 0.7458, 0.5464, 0.6944, 0.8088, 0.2945, 0.8648, 0.1688,
          0.3534],
         [0.3706, 0.5675, 0.9595, 0.6452, 0.7709, 0.2298, 0.1510, 0.2425, 0.8819,
          0.5867],
         [0.1070, 0.6552, 0.2062, 0.3814, 0.6594, 0.4250, 0.4623, 0.7210, 0.9497,
          0.3176],
         [0.1693, 0.5473, 0.4224, 0.8215, 0.6750, 0.6834, 0.0144, 0.0734, 0.5473,
         


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [12]:
# Perform matmul on tensor_A and tensor_B
multiplied = r3.mm(r4.T)
multiplied, multiplied.shape

(tensor([[1.5124, 1.4594, 2.5842, 1.7753, 2.7704, 2.8832, 2.2848, 1.5207, 2.3885,
          2.3596],
         [1.5606, 0.9245, 1.9186, 1.8308, 2.6693, 2.7930, 2.1966, 1.4799, 2.0527,
          2.4576],
         [1.3541, 1.5156, 2.3061, 1.9311, 2.9460, 2.4374, 3.1448, 1.9237, 2.3092,
          3.0621],
         [1.2360, 1.0599, 0.9872, 1.3394, 2.0301, 1.4348, 1.8568, 1.4793, 1.2610,
          2.2232],
         [1.1794, 0.9751, 2.0978, 1.2369, 2.1931, 2.0071, 1.1907, 1.2207, 1.3557,
          1.8430],
         [0.5776, 0.8641, 1.3160, 0.8686, 1.2898, 1.5691, 1.4370, 0.7900, 0.9248,
          1.2945],
         [1.5152, 1.0485, 1.9391, 1.6062, 2.5914, 2.2611, 1.8516, 1.2874, 1.6171,
          2.5944],
         [2.0781, 1.6831, 2.3941, 2.0188, 2.5682, 2.4706, 2.4266, 1.7329, 1.9078,
          2.5072],
         [1.8292, 1.6127, 2.2697, 1.8163, 2.5743, 1.6842, 1.9396, 1.6917, 2.0821,
          2.3462],
         [1.5572, 1.2838, 2.1110, 1.7196, 2.0130, 2.2352, 1.9693, 1.2112, 1.8557,
         

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
max = multiplied.max()
# Find min
min = multiplied.min()

min, max


(tensor(0.5776, device='cuda:0'), tensor(3.1448, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [15]:
# Find arg max
max_index = multiplied.argmax()

# Find arg min
min_index = multiplied.argmin()

min_index, max_index


(tensor(50, device='cuda:0'), tensor(26, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [16]:
# Set seed
torch.manual_seed(7)

# Create random tensor
r5 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
r5_squeezed = r5.squeeze()

# Print out tensors and their shapes
print(r5, r5.shape)
print(r5_squeezed, r5_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
