In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.1+cu117


## Introduction to Tensors

### Creating Tensors

In [2]:
scaler = torch.tensor(7)

scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
scaler.item()

7

In [5]:
vector = torch.tensor([7, 7])

vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
MATRIX = torch.tensor([[7, 8], [9, 10]])

MATRIX.ndim

2

In [8]:
MATRIX[0]

tensor([7, 8])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

In [14]:
random_tensor = torch.rand(3, 4)

In [15]:
random_tensor.ndim

2

In [16]:
random_tensor.shape

torch.Size([3, 4])

In [17]:
random_tensor

tensor([[0.3060, 0.8553, 0.8021, 0.8980],
        [0.8240, 0.1368, 0.4621, 0.5463],
        [0.2919, 0.1832, 0.3287, 0.9193]])

In [18]:
# Create random image size tensor
random_image_size_tensor = torch.rand(
    size=(224, 224, 3)
)  # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [19]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### Create a range of tensors and tensors like

In [22]:
one_to_ten = torch.arange(start=1, end=10, step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tendor datatypes

In [24]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0], dtype=None, device="cuda", requires_grad=False
)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [27]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [28]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [31]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32, device="cuda")

In [32]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

### Getting Information from Tensors

In [36]:
float_32_tensor.dtype, float_32_tensor.shape, float_32_tensor.device

(torch.float32, torch.Size([3]), device(type='cuda', index=0))

In [43]:
some_tensor = torch.rand(3, 4, device="cuda", dtype=torch.double)

print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

Datatype: torch.float64
Shape: torch.Size([3, 4])
Device: cuda:0


### Manipulating Tensors

In [56]:
tensor = torch.tensor([1, 2, 3])
tensor + 1


tensor([2, 3, 4])

In [57]:
tensor * 10

tensor([10, 20, 30])

In [58]:
tensor - 1

tensor([0, 1, 2])

In [68]:
tensor / 0.1


tensor([10., 20., 30.])

In [60]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [62]:
torch.sub(tensor, 1)

tensor([0, 1, 2])

In [64]:
torch.add(tensor, 20)

tensor([21, 22, 23])

In [67]:
torch.div(tensor, 0.2)


tensor([ 5., 10., 15.])

### Matrix Multiplication (dot product)

In [74]:
tensor = [1, 2, 3]

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [85]:
## Matrix multiplication by hand

tensor[0] * tensor[0] + tensor[1] * tensor[1] + tensor[2] * tensor[2]

tensor(14)

In [81]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.49 ms, sys: 0 ns, total: 1.49 ms
Wall time: 948 µs


In [83]:
%%time
value = torch.matmul(tensor, tensor)
print(value)

tensor(14)
CPU times: user 674 µs, sys: 400 µs, total: 1.07 ms
Wall time: 788 µs


In [91]:
tensor @ tensor


tensor(14)

In [102]:
# Tensor takes the shape of the outer, inner must match
tensor = torch.matmul(torch.rand(2, 3), torch.rand(3, 5))
tensor


tensor([[0.3645, 0.2569, 0.4286, 0.3009, 0.3011],
        [0.6096, 0.8013, 0.7813, 0.4612, 0.8026]])

In [122]:
# Shapes for matrix multiplicaion
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])

# Transpose
tensor_B, tensor_B.T


(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [123]:
torch.mm(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Tensor Aggregation (min, max, mean, sum, etc)

In [151]:
x = torch.arange(0, 100, 10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [133]:
torch.min(x), x.min()


(tensor(0.), tensor(0.))

In [134]:
torch.max(x), x.max()


(tensor(90.), tensor(90.))

In [146]:
torch.mean(x.type(torch.float)), x.type(torch.float).mean()


(tensor(45.), tensor(45.))

In [148]:
torch.median(x), x.median()


(tensor(40), tensor(40))

In [150]:
torch.sum(x), x.sum()


(tensor(450), tensor(450))

### Find positional min and max

In [158]:
torch.argmin(x), x.argmin()


(tensor(0), tensor(0))

In [159]:
torch.argmax(x), x.argmax()


(tensor(9), tensor(9))

In [160]:
x[torch.argmax(x)].item()


90

## Reshaping, stacking, squeezing and unsqueezing tensors

In [176]:
x = torch.arange(1.0, 10)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [178]:
# Add dimension
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [180]:
z = x.view(9, 1)
z, z.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [183]:
z[:, 0] = 5
x, z


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.]]))

In [193]:
# Stacking tensors

x_stacked = torch.stack([x, x, x], dim=0)
x_stacked

# You can also use vstack and hstack


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [199]:
z, z.squeeze()


(tensor([[5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.]]),
 tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]))

In [217]:
z, z.unsqueeze(dim=1), z.shape, z.unsqueeze(dim=1).shape


(tensor([[5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.]]),
 tensor([[[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]]]),
 torch.Size([9, 1]),
 torch.Size([9, 1, 1]))

In [220]:
x_original = torch.rand(224, 224, 3)  # Image

x_original.shape

torch.Size([224, 224, 3])

In [226]:
x_original.permute(2, 0, 1).shape


torch.Size([3, 224, 224])

## Indexing

In [229]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [231]:
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [237]:
x[0, 0], x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [238]:
x[0, 0, 0], x[0][0][0]

(tensor(1), tensor(1))

In [244]:
x[:, 1]

tensor([[4, 5, 6]])

In [243]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [247]:
x[:, 1, 1]

tensor([5])

In [248]:
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

In [256]:
array = np.arange(1.0, 8.0, dtype=np.float32)
tensor = torch.from_numpy(array)
array, tensor, tensor.dtype


(array([1., 2., 3., 4., 5., 6., 7.], dtype=float32),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [258]:
array = array + 1
array, tensor


(array([3., 4., 5., 6., 7., 8., 9.], dtype=float32),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [261]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [262]:
tensor = tensor + 1
tensor, numpy_tensor


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

In [272]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.3125, 0.2621, 0.6430, 0.0563],
        [0.9927, 0.4805, 0.9235, 0.2677],
        [0.4762, 0.0984, 0.6864, 0.0634]])
tensor([[0.4628, 0.2695, 0.3334, 0.0864],
        [0.7114, 0.2020, 0.1750, 0.0174],
        [0.6222, 0.0017, 0.5813, 0.6335]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [276]:
SEED = 11

torch.manual_seed(SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])
tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running on GPUs

In [277]:
!nvidia-smi

Fri Mar 17 13:06:21 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:0C:00.0  On |                  N/A |
| 41%   40C    P5    33W / 175W |   1056MiB /  8192MiB |     11%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [280]:
torch.cuda.is_available()


True

### Device Agnotsic Code

In [285]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
torch.device(device)


cuda


device(type='cuda')

In [284]:
torch.cuda.device_count()


1

## Putting tensors (and models) on the GPU

In [288]:
tensor = torch.tensor([1, 2, 4])
tensor.device


device(type='cpu')

In [289]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 4], device='cuda:0')

### Moving back to CPU

In [292]:
# To use with NumPy, tensor must be on CPU
tensor_on_gpu.to("cpu").numpy()


array([1, 2, 4])